{% set name = "amundsen-common" %}
{% set version = "0.32.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/amundsen-common-{{ version }}.tar.gz
  sha256: 88dcf7c8a43701385e99e4790c2e98f39f6680a8277d0e99819cb348db84a5f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - flask >=2.2.5
    - attrs >=19.0.0
    - marshmallow >=3.0
    - marshmallow3-annotations >=1.1.0

test:
  imports:
    - amundsen_common
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/amundsen-io/amundsen/tree/main/common
  summary: Common code library for Amundsen
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - rxm7706
